name: "Bug Report"
description: "Report a bug to help us improve the project."
title: "[Bug]: "
labels: ["bug"]
projects: ["ThetHtar-Vivian/group9_population_reports"]
assignees:
  - ThetHtar-Vivian
  - Aung-Paing-Khant
  - Ye-Wint-Thu
  - ThinYuShwe
  - Kyvelyin
  - Kyaw-Zayar-Thein

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Describe the issue and what you expected to happen."
      placeholder: "Example: The app crashes when clicking the Login button."
    validations:
      required: true

  - type: dropdown
    id: app-version
    attributes:
      label: "App Version"
      description: "Select the version you're using."
      options:
        - "1.0.0"
        - "1.1.0"
        - "1.2.0"
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs"
      description: "Paste any error messages or logs. They will be formatted automatically."
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      placeholder: "Anything else we should know?"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true